### ISSUE TITLE
Provided link is not working

### ISSUE THREAD

**Issue by swapn652** [itsmeShC/shc-resume#8]
![image](https://user-images.githubusercontent.com/70851202/196131431-9250f026-84ce-43f4-a726-493181789d16.png)

**Comment by itsmeShC** [comment]
> ![image](https://user-images.githubusercontent.com/70851202/196131431-9250f026-84ce-43f4-a726-493181789d16.png)

Solved! Changed the Domain to : resume.noobtodev.com
